# name: GitHub actions demo
# run-name: Testing our Github actions

# on: [push]

# jobs:
#   basic_workflow:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Job basic_workflow is executing as part of new workflow"


name: GitHub actions demo
run-name: Testing our Github actions with env

on: [push]

env:
  owner_name: ABhi

jobs:
  basic_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job basic_workflow is executing as part of new workflow - from $owner_name"
