name: Event-based workflow execution

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  fork:
    branches:
      - main
      
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Trigger
        run: echo "TRIGGERED the main branch workflow - event based - for event ${{ github.event_name }}"
      
      - name: Set Event Name Variable
        run: echo "EVENT_NAME=${{ github.event_name }}" >> $GITHUB_ENV

      - name: Set Test Event Name Variable
        run: echo "TEST_EVENT_NAME=${{ github.event_name }}"

      - name: Print Event Name
        run: echo "The event name is $EVENT_NAME, test event is $TEST_EVENT_NAME"

  reuse_job:
    uses: ./.github/workflows/reuseme.yml

  trigger_jenkins_job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins echotest job
        run: curl -X POST "http://18.208.222.228:8080/job/echotest/build" --user "admin:$JENKINS_API_KEY"
        env: 
          JENKINS_API_KEY: ${{ secrets.JENKINS_API_KEY }}
